version: '3.9'

services:
  db:
    image: mysql:8.0.35
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./wp-backup:/wp-backup
    environment:
      MYSQL_DATABASE: success
      MYSQL_USER: success
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret

  wordpress:
    depends_on:
      - db
    image: wordpress:6.4.3
    restart: always
    volumes:
      - ./:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: success
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: secret
    ports:
      - "8002:80"

volumes:
  db_data:
